### PR TITLE
P4-3161: add claim code spans with ids

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

# For the Reviewee

## Summary
PostMaster claim code page now includes its data fields as <span>s with IDs in them for easy DOM parsing for RobotFramework.

#### Release Note
Tweaks to help with automated QA.

#### Breaking Changes
None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

*Steps to test your application for someone not familiar with it.* Required.

PM Claim Code page now lists the data fields without their label text as <spans> with IDs.
The values themselves will still need to be trimmed of whitespace; that is something built-in that cannot be removed so easily, but is not required since scripts already do a lot of parsing on this page.

### CODE REVIEW

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12.11-P4-3161

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.12.11-P4-3161

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12.11-P4-3161-generic

**Review by rsdunya — APPROVED** [review]

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12.11-P4-3161

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12.11-P4-3161-generic

**Pull request merged**
