### PR TITLE
P4-3665: ensure menu-area takes up full height even when no menus.

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

# For the Reviewee

## Summary
Org picker should be at top of page even when no menus available.

#### Release Note
Org picker now afixed to the top of page even when no menus available.

#### Breaking Changes
None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

On Dev instance:
1. ensure you have multiple org access
2. logout
3. login
4. while at the "org choose"  page with different buttons per org you belong to, ensure the org picker is at the top of the page (there should be no menus availabe apart from the ... and Logout).

### CODE REVIEW

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.14-P4-3665

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.14-P4-3665-generic

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.14-P4-3665

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:4.0.14

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3665

**Review by rsdunya — APPROVED** [review]

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.14-P4-3665

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.14-P4-3665-generic

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.14-P4-3665

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:4.0.14

**Pull request merged**
