### PR TITLE
P4-3831: add SSO/Keycloak support.

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

# For the Reviewee

## Summary
Add minimal SSO support for a keycloak provider. Also add last seen timestamp to PM channel details page.

#### Release Note
Add minimal SSO support for a keycloak provider. Also add last seen timestamp to PM channel details page.

#### Breaking Changes
None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

*Steps to test your application for someone not familiar with it.* Required.

1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command

### CODE REVIEW

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/rapidpro:ci-4.0.14-P4-3434-generic

**Comment by ist-qa** [comment]
Python/NPM Libs Image built: istresearch/p4-engage:pylibs-amd64-6cea18d65126b235dfbd3f9ce865c092

**Comment by ist-qa** [comment]
Python/NPM Libs Image built: istresearch/p4-engage:pylibs-arm64-6cea18d65126b235dfbd3f9ce865c092

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Python/NPM Libs Image built: istresearch/p4-engage:pylibs-amd64-6cea18d65126b235dfbd3f9ce865c092

**Comment by ist-qa** [comment]
Python/NPM Libs Image built: istresearch/p4-engage:pylibs-arm64-6cea18d65126b235dfbd3f9ce865c092

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/rapidpro:ci-4.0.14-P4-3434-generic

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/rapidpro:ci-4.0.14-P4-3434-generic

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.14-P4-3434

**Comment by ist-qa** [comment]
Container built: istresearch/rapidpro:ci-4.0.14-P4-3434-generic

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:ci-4.0.14-P4-3434

**Review by andrewkcarter — APPROVED** [review]

**Pull request merged**
