### PR TITLE
P4 1471 - Channel Management Page Updates

### PR DESCRIPTION
**Pull request by rsdunya**
### Changes:

1. The following columns were removed:
•“Created On” 
•“Modified On”
•“Urn Schemes”

2. These columns were renamed
•“Channel Type” to “Type”
•“Unique Identifier” to “UUID”

3. A new "Channel Log" column that links to the Channel's log page was added.

4. A new "Settings" column that links to the Channel's settings page was added.

5. The (+) add button was removed and replaced with a settings dropdown menu.

6. The default sort is based on the Channel creation date in descending order.
Screen Shot 2020-05-19 at 4 34 45 PM

### CODE REVIEW

**Comment by andrewkcarter** [comment]
What does _Add Classifier_ do, and how do import/export work? Does it export the full channel configuration? And import, does that fully restore channels? @rsdunya

**Comment by rsdunya** [comment]
> What does _Add Classifier_ do, and how do import/export work? Does it export the full channel configuration? And import, does that fully restore channels? @rsdunya

Hey @andrewkcarter I left it that way since @carricklongley mentioned to use the settings menu from the org/home page and thats how it is there. Otherwise the dropdown didn't make much sense at this time since there was only one feature. I.e 2 clicks for one feature.

**Comment by andrewkcarter** [comment]
Add Classifier, import, and export need to be removed if irrelevant, or implemented and tested if they are relevant.

**Comment by rsdunya** [comment]
> Add Classifier, import, and export need to be removed if irrelevant, or implemented and tested if they are relevant.

@andrewkcarter Hey I removed those unnecessary menu items and updated the screenshot on this PR.

**Pull request merged**
