### PR TITLE
P4-3189: Select All available even when no checkboxes to select

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

# For the Reviewee

<Reminder PR Title should be JIRA_NUMBER and Useful Description>

## Summary
Description of changes.

#### Release Note
<Concise sentence describing change>Required.

#### Breaking Changes
<Description for Techops of how to handle changes, migrations, updates>None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

*Steps to test your application for someone not familiar with it.* Required.

1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command

### CODE REVIEW

**Review by rsdunya — COMMENTED** [review]
```
                - if actions
                  -if org_perms.msgs.msg_update or org_perms.msgs.broadcast_send
                    %tr.multiselect-header
                      %th{style: 'padding-left:0px'}
                        %a.multiselect-select-all.checkbox.object-row-checkbox.glyph.icon-checkbox-unchecked.contact-checkbox.object-row-checkbox{style: 'padding-left: 5px'}
                        %div
                          Select all
```

Try that one.

**Comment by ist-qa** [comment]
RP App Image built: istresearch/p4-engage:rpapp-ci-4.0.11-P4-3189

**Review by rsdunya — APPROVED** [review]

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.11-P4-3189

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.11-P4-3189

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.11-P4-3189-generic

**Pull request merged**
