### PR TITLE
Branding Updates

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

## Summary
Fixing the "generic" branding as none of that was tested before now.
Added to the "engage":  header color matching, org picker not restricted to 30 chars, org picker list item clickable anywhere in the item, not just the text of the org name, and lastly, added a version string just under the logo when logged in.

#### Release Note
Visual update to the header area for a better UX.

#### Breaking Changes
None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

*Steps to test your application for someone not familiar with it.* Required.

1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command

### CODE REVIEW

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12.5-versioning

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12.5-versioning

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.12.5-versioning

**Review by rsdunya — APPROVED** [review]

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12.5-versioning

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12.5-versioning

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12.5-versioning-generic

**Pull request merged**
