### PR TITLE
P4-3380: Restore Purge Outbox in UI

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

## Summary
Purge Outbox button in UI recreated with new framework code.

#### Release Note
Purge Outbox button re-added to the UI.

#### Breaking Changes
None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

Go to a channel's details page.
See Purge Outbox button.
Bonus: See Edit button.
Additional Bonus: See your wide-screen monitor get some love.

### CODE REVIEW

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12-P4-3380-generic

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12-P4-3380-generic

**Comment by ist-qa** [comment]
Python App Image built: istresearch/p4-engage:pyapp-ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/p4-engage:ci-4.0.12-P4-3380

**Comment by ist-qa** [comment]
Image built: istresearch/rapidpro:ci-4.0.12-P4-3380-generic

**Review by rsdunya — APPROVED** [review]

**Pull request merged**
