### PR TITLE
P4-3674: enhanced superadmin manage orgs page

### PR DESCRIPTION
**Pull request by baracudda**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

# For the Reviewee

## Summary
Superadmins page to manage orgs now lists a button for org creation and sorts them by name rather than credits.

#### Release Note
Superadmins page to manage orgs now lists a button for org creation and sorts them by name rather than credits.

#### Breaking Changes
None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

Login as a superadmin
go to the Workspaces page
note the workspaces are listed in name order
note the new "New Workspace" button

on the New Workspace page, the credits option now lists a "Do not use" option as default; if you create an org with this new option, topups will not be used by the org at all.

### CODE REVIEW

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.15.2-P4-3674

**Comment by ist-qa** [comment]
Container built: istresearch/rapidpro:ci-4.0.15.2-P4-3674-generic

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:ci-4.0.15.2-P4-3674

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:pyapp-ci-4.0.15.2-P4-3674

**Comment by ist-qa** [comment]
Container built: istresearch/rapidpro:ci-4.0.15.2-P4-3674-generic

**Comment by ist-qa** [comment]
Container built: istresearch/p4-engage:ci-4.0.15.2-P4-3674

**Review by rsdunya — APPROVED** [review]

**Pull request merged**
